### ISSUE TITLE
The application crashes when i click on Select From camera

### ISSUE THREAD

**Issue by 44asad** [7LPdWcaW/GrowTracker-Android#96] opened 2019-06-30 13:40 UTC
### Expected behavior:
I expected that the application should not be crash when i click on  select an option from camera.

### Actual behavior:
After configure the application when i click on select an option from camera. application is you can see in bug vieo proprealy.

### How to reproduce:
1.Download the app from playstore and open the app.
2. Then click no [+] icon
3.Add New plant & 
4.Naw Click On photo option
5.Then Select from camera
6.Note the Bug.

### information
* App version:v2.5.1
* os:Android 6.0.1
* Device:samsung J5
### Recording of the bug
https://youtu.be/nzY4-7jKMcM
### Logcat:
<pre><code>06-30 05:50:56.323 32009 32009 E AndroidRuntime: FATAL EXCEPTION: main
06-30 05:50:56.323 32009 32009 E AndroidRuntime: Process: me.anon.grow, PID: 32009
06-30 05:50:56.323 32009 32009 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=android:fragment:1, request=1, result=0, data=null} to activity {me.anon.grow/me.anon.grow.PlantDetailsActivity}: java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
06-30 05:50:56.323 32009 32009 E AndroidRuntime:   at android.app.ActivityThread.deliverResults(ActivityThread.java:4927)
06-30 05:50:56.323 32009 32009 E AndroidRuntime:   at android.app.ActivityThread.handleSendResult(ActivityThread.java:4970)
06-30 05:50:56.323 32009 32009 E AndroidRuntime:   at android.app.ActivityThread.access$1600(ActivityThread.java:223)
06-30 05:50:56.323 32009 32009 E AndroidRuntime:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1851)
06-30 05:50:56.323 32009 32009 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:102)
06-30 05:50:56.323 32009 32009 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:158)
06-30 05:50:56.323 32009 32009 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:7231)
06-30 05:50:56.323 32009 32009 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
06-30 05:50:56.323 32009 32009 E AndroidRuntime:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
06-30 05:50:56.323 32009 32009 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
06-30 05:50:56.323 32009 32009 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
06-30 05:50:56.323 32009 32009 E AndroidRuntime:   at java.util.ArrayList.get(ArrayList.java:310)
06-30 05:50:56.323 32009 32009 E AndroidRuntime:   at me.anon.grow.fragment.PlantDetailsFragment.onActivityResult(PlantDetailsFragment.java:445)
06-30 05:50:56.323 32009 32009 E AndroidRuntime:   at android.app.Activity.dispatchActivityResult(Activity.java:7162)
06-30 05:50:56.323 32009 32009 E AndroidRuntime:   at android.app.ActivityThread.deliverResults(ActivityThread.java:4923)
06-30 05:50:56.323 32009 32009 E AndroidRuntime:   ... 9 more</code></pre>

**Comment by 7LPdWcaW** [comment] 2019-06-30 13:53
Duplicate of #87

**Closed by 7LPdWcaW** 2019-06-30 13:53 UTC
Labels: duplicate
