### ISSUE TITLE
Bug: App crashed when I was trying to add image through camera and press phone back button

### ISSUE THREAD

**Issue by darewealth** [7LPdWcaW/GrowTracker-Android#95] opened 2019-06-29 12:36 UTC
### Describe the bug.
When I tried to use the camera option to add plant on the app, I clicked on the image feature and add with camera, after I took a shot on my camera, I decided to change the image and I pressed the cancel * button, and press back then the app crashed. 

### Steps to reproduce.
* Launch the app

* Click on the plant you added

* Click on photo feature at the top by the right

* Then select 'from camera' and snap
* 
Click X to cancel the picture and press phone back button

* And note the bug

### Expected Behaviour
I expect to use the app with issues like this. Even if I want to change or cancel an image, I don't expect this to happen.

### Screen recording.
https://youtu.be/ry0MYX86k3Y

### Devices and Versions.
Device: [Gionee X1]

Version [7.0]

App version [2.5.1]

### Log
```{"additionalMessage":"java.lang.RuntimeException: Failure delivering result ResultInfo{who\u003dandroid:fragment:1, request\u003d1, result\u003d0, data\u003dnull} to activity {me.anon.grow/me.anon.grow.PlantDetailsActivity}: java.lang.ArrayIndexOutOfBoundsException: length\u003d10; index\u003d-1\n\tat android.app.ActivityThread.deliverResults(ActivityThread.java:4188)\n\tat android.app.ActivityThread.handleSendResult(ActivityThread.java:4231)\n\tat android.app.ActivityThread.-wrap20(ActivityThread.java)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)\n\tat android.os.Handler.dispatchMessage(Handler.java:110)\n\tat android.os.Looper.loop(Looper.java:203)\n\tat android.app.ActivityThread.main(ActivityThread.java:6269)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)\nCaused by: java.lang.ArrayIndexOutOfBoundsException: length\u003d10; index\u003d-1\n\tat java.util.ArrayList.get(ArrayList.java:413)\n\tat me.anon.grow.fragment.PlantDetailsFragment.onActivityResult(PlantDetailsFragment.java:445)\n\tat android.app.Activity.dispatchActivityResult(Activity.java:6948)\n\tat android.app.ActivityThread.deliverResults(ActivityThread.java:4184)\n\t... 9 more\n\r\n","exception":{"cause":{"detailMessage":"length\u003d10; index\u003d-1","stackTrace":[{"declaringClass":"java.util.ArrayList","fileName":"ArrayList.java","lineNumber":413,"methodName":"get"},{"declaringClass":"me.anon.grow.fragment.PlantDetailsFragment","fileName":"PlantDetailsFragment.java","lineNumber":445,"methodName":"onActivityResult"},{"declaringClass":"android.app.Activity","fileName":"Activity.java","lineNumber":6948,"methodName":"dispatchActivityResult"},{"declaringClass":"android.app.ActivityThread","fileName":"ActivityThread.java","lineNumber":4184,"methodName":"deliverResults"},{"declaringClass":"android.app.ActivityThread","fileName":"ActivityThread.java","lineNumber":4231,"methodName":"handleSendResult"},{"declaringClass":"android.app.ActivityThread","fileName":"ActivityThread.java","lineNumber":-1,"methodName":"-wrap20"},{"declaringClass":"android.app.ActivityThread$H","fileName":"ActivityThread.java","lineNumber":1593,"methodName":"handleMessage"},{"declaringClass":"android.os.Handler","fileName":"Handler.java","lineNumber":110,"methodName":"dispatchMessage"},{"declaringClass":"android.os.Looper","fileName":"Looper.java","lineNumber":203,"methodName":"loop"},{"declaringClass":"android.app.ActivityThread","fileName":"ActivityThread.java","lineNumber":6269,"methodName":"main"},{"declaringClass":"java.lang.reflect.Method","fileName":"Method.java","lineNumber":-2,"methodName":"invoke"},{"declaringClass":"com.android.internal.os.ZygoteInit$MethodAndArgsCaller","fileName":"ZygoteInit.java","lineNumber":1063,"methodName":"run"},{"declaringClass":"com.android.internal.os.ZygoteInit","fileName":"ZygoteInit.java","lineNumber":924,"methodName":"main"}],"suppressedExceptions":[]},"detailMessage":"Failure delivering result ResultInfo{who\u003dandroid:fragment:1, request\u003d1, result\u003d0, data\u003dnull} to activity {me.anon.grow/me.anon.grow.PlantDetailsActivity}: java.lang.ArrayIndexOutOfBoundsException: length\u003d10; index\u003d-1","stackTrace":[{"declaringClass":"android.app.ActivityThread","fileName":"ActivityThread.java","lineNumber":4188,"methodName":"deliverResults"},{"declaringClass":"android.app.ActivityThread","fileName":"ActivityThread.java","lineNumber":4231,"methodName":"handleSendResult"},{"declaringClass":"android.app.ActivityThread","fileName":"ActivityThread.java","lineNumber":-1,"methodName":"-wrap20"},{"declaringClass":"android.app.ActivityThread$H","fileName":"ActivityThread.java","lineNumber":1593,"methodName":"handleMessage"},{"declaringClass":"android.os.Handler","fileName":"Handler.java","lineNumber":110,"methodName":"dispatchMessage"},{"declaringClass":"android.os.Looper","fileName":"Looper.java","lineNumber":203,"methodName":"loop"},{"declaringClass":"android.app.ActivityThread","fileName":"ActivityThread.java","lineNumber":6269,"methodName":"main"},{"declaringClass":"java.lang.reflect.Method","fileName":"Method.java","lineNumber":-2,"methodName":"invoke"},{"declaringClass":"com.android.internal.os.ZygoteInit$MethodAndArgsCaller","fileName":"ZygoteInit.java","lineNumber":1063,"methodName":"run"},{"declaringClass":"com.android.internal.os.ZygoteInit","fileName":"ZygoteInit.java","lineNumber":924,"methodName":"main"}],"suppressedExceptions":[]},"manufacturer":"GIONEE","model":"X1","osVersion":"7.0","packageName":"me.anon.grow","timestamp":1561760984357,"version":"2.5","versionCode":"21"}```

**Comment by 7LPdWcaW** [comment] 2019-06-29 15:35
Duplicate of #87

**Closed by 7LPdWcaW** 2019-06-29 15:35 UTC
