### ISSUE TITLE
Light schedule error

### ISSUE THREAD

**Issue by Maxtille** [7LPdWcaW/GrowTracker-Android#225] opened 2020-06-11 10:21 UTC
Hi, as my light is sucking a lot of current and as the electricity is cheaper by night I've been used to light my plants by night. Eg from 20h00 to 8h00 in the next morning during flowering. But the garden light schedule from grow tracker doesn't seem to accept it since my from hour is later than my to hour. 
I think it should ask the power on hour and duration of the cycle instead. It would solve my problem

**Comment by 7LPdWcaW** [comment] 2020-06-12 15:51
![Screenshot_20200612-164905](https://user-images.githubusercontent.com/13586344/84521380-d4b29280-accc-11ea-8917-36dc9390cb8e.png)
![Screenshot_20200612-164923](https://user-images.githubusercontent.com/13586344/84521381-d54b2900-accc-11ea-8d29-b2e20b516914.png)

I'm not seeing this issue, are you able to send me a screenshot? what are you expecting to happen in the app?

**Comment by rendeko** [comment] 2020-06-26 02:03
I am also struggling with this. My ideal is to have Lights On at 3:00, and Lights Off at 1:00, a 22 hour light schedule. The slider starts at 1.75h of light. The expected behavior is that when I drag the slider to any position, it saves on that position. However, it only saves when the slider is before 21h of light. Past that, it resets to 1.75h of light when the page is refreshed.

This occurs on v2.6.1

**Comment by 7LPdWcaW** [comment] 2020-06-27 14:21
I _may_ need to mark this as a wont fix. Unfortunately the way i've chosen to structure the data here means its impossible for me to know if its 1.75h of light or 21h of light as I only know the "on" time and the "off" time (which will always be just what you set). The slider was more for visual than actually setting the time. Works best for when you set the on time but cant figure out what + 18hrs is because Im rubbish at it.

I will need to rethink how to approach this in the next version, perhaps I store only the "on" time with a number of hours "on" and same for the off time

**Comment by 7LPdWcaW** [comment] 2020-07-18 19:31
I'm going to mark this as wont fix. The slider was designed as more of a visual representation of the on/off date and to give you the ability to work out the off or on time after providing one or the other and then sliding the slider.

Im going to re-think this in the future version to ensure it works correctly

**Closed as completed by 7LPdWcaW** 2020-07-18 19:31 UTC
Labels: wontdo
